version: "3.7"
services:
    app:
        platform: linux/x86_64
        container_name: app_maschit_back
        image: app_maschit_back
        ports:
            - 8876:80
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./:/var/www/html
#            - ./docker/php.ini:/usr/local/etc/php/php.ini
#            - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
        networks:
            default:
                ipv4_address: 172.29.0.2
#    db:
#        platform: linux/x86_64
#        container_name: db_uzinfocom_new_back
#        image: postgres:14.5-alpine
#        restart: unless-stopped
#        environment:
#            POSTGRES_DATABASE: "${DB_DATABASE}"
#            POSTGRES_PASSWORD: "${DB_PASSWORD}"
#            POSTGRES_USER: "${DB_USERNAME}"
#            POSTGRES_HOST_AUTH_METHOD: "trust"
#            POSTGRES_ALLOW_EMPTY_PASSWORD: 1
#            POSTGRES_ROOT_PASSWORD: "root"
#        volumes:
#            - ./docker/postgres:/var/lib/postgresql/data
#        ports:
#            - 8101:5432
#        networks:
#            default:
#                ipv4_address: ${NETWORK_DEFAULT}.3
#    pgadmin:
#        platform: linux/x86_64
#        container_name: pgadmin_uzinfocom_back
#        image: dpage/pgadmin4
#        ports:
#            - 5050:80
#        environment:
#            PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
#            PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
#            PGADMIN_CONFIG_SERVER_MODE: 'False'
#        depends_on:
#            - db
#        volumes:
#            - ./docker/pgadmin:/var/lib/pgadmin4
#        networks:
#            default:
#                ipv4_address: ${NETWORK_DEFAULT}.4
volumes:
    postgres:
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.29.0.0/16
                  gateway: 172.29.0.1
